### ISSUE TITLE
A few comments from reading the new docs

### ISSUE THREAD

**Issue by bnmnetp** [DavidVujic/python-polylith-docs#1]
Thanks for doing this.. It is always super hard for me to make myself work on documentation.  Here are a few suggestions based on little things I ran into while trying o get set up initially

- [x] A note on `poetry init` and the package name, whether it matters or not.  I wasn't sure.
- [x] A note or a link  to a bit more on the projects / namespace issue.   It can seem a bit mysterious how we can ignore bases and dump to the namespace, maybe mentioning that poetry shell adds bases and components and the top level directory to your PYTHONPATH
- [x] Also it would be good to note that when you pick your namespace it should not be the same as another python package you might be importing.  Its obvious now, but I didn't think about it when configuring the project
- [ ] Are there tools/commands to keep the top level pyproject.toml file in sync with the individual projects?   It seems necessary, but maybe I'm missing something.

I have a project bookserver that we publish on PyPI and has everything under the bookserver namespace.   It seems like I would want to use --with-top-namespace = ""  ?? To avoid having everything under the namespace I've defined in my polylith project - how to keep them compatible?  Maybe the move to polylith will require a change to the API adding a top-level namespace.?

**Comment by bnmnetp** [comment]
It may be beyond the scope of what you want to do, but a note or link in the migration section that gives someone some pointers on how to move their code to a new git repo without losing all of the history would be helpful.  This one seems OK, but not great.  
https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b

**Comment by DavidVujic** [comment]
Thank you, much appreciated!

**Comment by DavidVujic** [comment]
About publishing to PyPI:

Yes, as you write, all libraries built from a Polylith workspace & published to PyPI will by default get the same namespace. And that will likely cause problems for those that install more than one of the libraries in the same virtual environment.

So I developed a workaround to support that kind of scenario. The `--with-top-namespace` flag will analyze the project-specific code (using the Python builtin `ast` feature) that should be built into a library, and actually prefix all imports with the namespace that is passed in to the flag. In addition to that, it will also put all bricks in a subfolder with that name, to avoid collisions with another library in the virtual environment.

This is done within the `build-project` command and the re-writes of modules is done only in the files ending up in a wheel or an sdist. It won't change the bases or components that are source controlled in the Polylith workspace.

You can try it and look in the wheel and/or sdist packages by running `poetry build-project --with-top-namespace my_custom_namespace` to get an idea on the output.

I totally understand that this thing might sound scary - some tool that is re-writing code 😄 - and that is why I added a disclaimer about libraries in the "Use cases" section. As an alternative to all this is to have library code living in a separate repo, outside of Polylith.

**Comment by bnmnetp** [comment]
After thinking through this more, I am less concerned...

The two libraries we publish we publish mainly so that you can run them as commands for example we published the runestone package on PyPI but mainly to make it easy to install and run `runestone build`   That API will not change.  The `bookserver` package is the same.

We do share some code, but that is internally. and it will actually be much better and easy to share as part of a Polylith than the hoops we jump through now to have multiple editable installations poetry projects working side by side.

**Comment by DavidVujic** [comment]
I have updated the docs - the Setup and Commands sections - with more details and I believe it covers the poetry init command, top namespace and python path-related information in more detail. Thank you again for your feedback! ⭐ 

I'll close this issue, and will open a new one about `Are there tools/commands to keep the top level pyproject.toml file in sync with the individual projects? It seems necessary, but maybe I'm missing something.`

I think that is a very good idea, and something the tooling could help out with in addition to the existing commands.

**Comment by DavidVujic** [comment]
Hello @bnmnetp!

I think that I have solved the last one of the checkboxes in this thread 😄 🙏 

Version 1.6.0 of the tooling was just released and I have added a new command: `poetry poly sync`.

Here's the docs:
https://davidvujic.github.io/python-polylith-docs/commands/#sync

**Comment by bnmnetp** [comment]
> Hello @bnmnetp!
> 
> 
> 
> I think that I have solved the last one of the checkboxes in this thread 😄 🙏 
> 
> 
> 
> Version 1.6.0 of the tooling was just released and I have added a new command: `poetry poly sync`.
> 
> 
> 
> Here's the docs:
> 
> https://davidvujic.github.io/python-polylith-docs/commands/#sync

that sounds Great!  Cant wait to give it a try soon.
